# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Macos Build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        #        os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ macos-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang, cl ]
        include:
          #          - os: windows-latest
          #            c_compiler: cl
          #            cpp_compiler: cl
          #          - os: ubuntu-latest
          #            c_compiler: gcc
          #            cpp_compiler: g++
          #          - os: ubuntu-latest
          #            c_compiler: clang
          #            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
#          - os: macos-latest
#            c_compiler: gcc
#            cpp_compiler: g++
        exclude:
          #          - os: windows-latest
          #            c_compiler: gcc
          #          - os: windows-latest
          #            c_compiler: clang
          #          - os: ubuntu-latest
          #            c_compiler: cl
          - os: macos-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: gcc

    steps:
      - uses: actions/checkout@v3

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install Qt on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install qt5
          brew install coreutils
          QT_INSTALL_PATH=$(greadlink -f $(brew --prefix qt))
          echo "QT_INSTALL_PATH=$QT_INSTALL_PATH" >> $GITHUB_ENV
          echo "PATH=$PATH:$QT_INSTALL_PATH/bin" >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo $QT_INSTALL_PATH

      - name: Configure mac CMake
        run: |
          export CMAKE_PREFIX_PATH=$(brew --prefix qt5)
          cmake -B build -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -S .

      - name: Build
        run: cmake --build build --config Release

      - name: upload Mac-QtReadELF-withQtEnv
        uses: actions/upload-artifact@v2
        with:
          name: Mac-QtReadELF-withQtEnv
          path: ${{github.workspace}}/build/QtReadELF.dmg

      - name: upload Mac-QtReadELF
        uses: actions/upload-artifact@v2
        with:
          name: Mac-QtReadELF
          path: ${{github.workspace}}/build/QtReadELF.app/Contents/MacOS/QtReadELF
  release:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload QtReadELF with QT env
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/build/QtReadELF.dmg
          asset_name: QtReadELF.dmg
          asset_content_type: application/x-diskcopy
      - name: Upload QtReadELF without QT env
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/build/QtReadELF.app/Contents/MacOS/QtReadELF
          asset_name: QtReadELF
          asset_content_type: application/x-diskcopy