# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Ubuntu Build

on:
  push:
    branches: [ "dev" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]
        c_compiler: [  clang ]
        include:
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v3
      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: Install Clang
        run: |
          sudo apt update
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          sudo apt install clang lldb lld -y
          clang --version
          clang++ --version
      - name: Install Qt on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install qtbase5-dev qt5-qmake
      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -S .
        env:
          CC: clang-14
          CXX: clang++-14

      - name: Build
        run: cmake --build build --config Release

      #      - name: Pack Ubuntu-QtReadElf-withQtEnv
#        run: |
#          touch {{github.workspace}}/default.desktop
#          > {{github.workspace}}/default.desktop
#          echo "[Desktop Entry]\nType=Application\nName=QtReadELF\nExec=AppRun %F\nIcon=default\nComment=Edit this default file\nTerminal=true\nCategories=Application;" >{{github.workspace}}/default.desktop
#          ${{github.workspace}}/../linux-pack/linuxdeployqt-continuous-x86_64.AppImage QtReadELF -appimage
#          mv QtReadELF-*.AppImage QtReadELF-WithQtEnv.AppImage
      - name: Upload Ubuntu-QtReadELF-withQtEnv
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu-QtReadELF-withQtEnv
          path: ${{github.workspace}}/build/QtReadELF-WithQtEnv.AppImage

      - name: upload Ubuntu-QtReadELF
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu-QtReadELF
          path: ${{github.workspace}}/build/QtReadELF

  release:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload QtReadELF with QT env
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/build/QtReadELF-WithQtEnv.AppImage
          asset_name: QtReadELF-WithQtEnv.AppImage
          asset_content_type: application/x-diskcopy
      - name: Upload QtReadELF without QT env
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/build/QtReadELF
          asset_name: QtReadELF
          asset_content_type: application/x-diskcopy